apiVersion: v1
name: rancher-rke2-custom-template
description: RKE2 Cluster template for Custom Kubernetes
version: 0.3.1
annotations:
  catalog.cattle.io/type: cluster-template
  catalog.cattle.io/namespace: fleet-default
